Readme.md, lib/parallel_tests/cli.rb, lib/parallel_tests/test/runner.rb, spec/integration_spec.rb
=> Add --combine-stderr flag

Readme.md, lib/parallel_tests/cli.rb, spec/parallel_tests/cli_spec.rb
separated from PR as discussed here: https://github.com/grosser/parallel_tests/pull/403#discussion_r32485749
=> support -- as -o option alternative [fix #402]

Readme.md
=> Add rspec-retry tip

lib/parallel_tests/cli.rb, lib/parallel_tests/test/runner.rb, spec/parallel_tests/test/runner_spec.rb
Add the option as discussed here https://github.com/grosser/parallel_tests/issues/431
=> Add unknown_runtime option with default = average

lib/parallel_tests/cli.rb, spec/integration_spec.rb, spec/parallel_tests/cli_spec.rb
In reference to this issue
https://github.com/grosser/parallel_tests/issues/452
=> Keep the rerun commands quiet without --verbose

lib/parallel_tests/cli.rb
=> fix the CLI again. :(

Readme.md
@grosser , please review - hope its up to your standard. Thanks for the great gem and keeping an active eye on the issues section.
=> Reformatted Tips Section & Added Entry For Cucumber ReportBuilder Gem

Readme.md
=> more readme styling

lib/parallel_tests.rb, spec/parallel_tests_spec.rb
Windows, Mac, Linux should work. Sought out well supported methods for querying this data. 
Basic tests to ensure that a value is returned, and that the value is of type string.
=> Added support for querying the parent pid 

Readme.md, lib/parallel_tests.rb, spec/parallel_tests_spec.rb
https://github.com/grosser/parallel_tests/issues/521
=> Adding last_process? method

.travis.yml, Readme.md, appveyor.yml, spec/integration_spec.rb, spec/parallel_tests/gherkin/runner_behaviour.rb, spec/parallel_tests/test/runtime_logger_spec.rb, spec/spec_helper.rb
This is a work in progress PR. AppVeyor has been set up for Windows CI but there are still lots of failures. Some are because the tests are written with load of OS specific assumptions, others because it does appear that the gem has Windows specific bugs.
Feel free to merge as is for visibility or help fix things.
Build link: https://ci.appveyor.com/project/enkessler/parallel-tests
=> Get the project working on Windows

lib/parallel_tests.rb, lib/parallel_tests/cli.rb, lib/parallel_tests/pids.rb, spec/parallel_tests/rspec/runner_spec.rb, spec/parallel_tests/test/runner_spec.rb, spec/parallel_tests_spec.rb
Fixes #617 
I tested this with my suite of Cucumber tests
=> Store reference to Tempfile with PIDs while it may be needed

lib/parallel_tests/tasks.rb
@ericpromislow 
fixes https://github.com/grosser/parallel_tests/issues/605
caused by https://github.com/grosser/parallel_tests/pull/590 fyi @hron 
idk why we don't always require it ... but I'll just guess there is a reason so not touching that ...
=> load library before using methods from it

Readme.md, lib/parallel_tests/cli.rb, lib/parallel_tests/test/runner.rb, spec/parallel_tests/cli_spec.rb
resolve https://github.com/grosser/parallel_tests/issues/641
=> add quiet option

Readme.md
Hello! Great project by the way! I was looking over the readme and noticed a minor typo. No biggie, just wanted to contribute something. This is my first contribution to an opensource project so thanks for taking the time to look at this. 
-Kyle
=> Fix typo in Readme

lib/parallel_tests/tasks.rb
fixes https://github.com/grosser/parallel_tests/issues/706
=> require the lib we are using

lib/parallel_tests/gherkin/listener.rb, lib/parallel_tests/pids.rb, spec/parallel_tests/gherkin/runner_behaviour.rb, spec/parallel_tests/test/runner_spec.rb
This PR eliminates some Ruby warnings.
=> Ruby Warnings

lib/parallel_tests/tasks.rb
I switched to the :sql schema format, and noticed that all of the rake sub-commands in `lib/parallel_tests/tasks.rb` were calling `rake` directly. This keeps loading the Rails environment for every test database during `rake parallel:prepare`. Spring adds a binstub to `bin/rake`:
```
#!/usr/bin/env ruby
begin
load File.expand_path('../spring', __FILE__)
rescue LoadError => e
raise unless e.message.include?('spring')
end
require_relative '../config/boot'
require 'rake'
Rake.application.run
```
So my change runs all of these rake tasks using the `./bin/rake` binstub, if it exists.
```
$ time rake parallel:prepare
=> Loading Rails application...
Running via Spring preloader in process 2582
(0.8ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY …
```
=> Run rake tasks with bin/rake if it exists, to use the Spring preloader

CHANGELOG.md
In the 3.0.0 release there should be no breaking changes other than this.
=> More accurate description of breaking changes

CHANGELOG.md
Hi!
I had to read through the previous releases when upgrading this gem for work so I figured I might as well document the changes in the change log. Thanks so much for your work maintaining this gem!
=> Update changelog to include releases 2.23.0 to 2.32.0

.github/workflows/test.yml
=> avoid CI warnings

lib/parallel_tests/cli.rb, spec/integration_spec.rb
=> Pluralize 'spec(s) per process'

Readme.md
=> Update README to remove incorrect command about running after migrations and add correct command

Readme.md
I've added GitLab support to the wiki page and adjusted the title.
Thank you for parallel_tests
=> Fix broken link after updating title

.github/workflows/test.yml, .rubocop.yml, CHANGELOG.md, Gemfile.lock, lib/parallel_tests/cli.rb, lib/parallel_tests/cucumber/scenario_line_logger.rb, lib/parallel_tests/gherkin/runner.rb, lib/parallel_tests/grouper.rb, parallel_tests.gemspec, spec/fixtures/rails60/Gemfile.lock, spec/fixtures/rails61/Gemfile.lock, spec/rails_spec.rb, spec/spec_helper.rb
fixes https://github.com/grosser/parallel_tests/issues/846
=> support old rubies because dependency management sucks

spec/parallel_tests/cli_spec.rb
=> Fix typo: corectly → correctly

.github/workflows/test.yml
Make is simple for contributors to run the GitHub actions on their fork
before opening a pull request.
=> Run GitHub actions on all branches

CHANGELOG.md
=> Cleanup extra CHANGELOG.md entry

lib/parallel_tests/tasks.rb
=> various task fixes

CHANGELOG.md, spec/parallel_tests/cucumber/scenarios_spec.rb, spec/parallel_tests/gherkin/runner_behaviour.rb, spec/parallel_tests/grouper_spec.rb, spec/parallel_tests/rspec/runner_spec.rb, spec/parallel_tests/tasks_spec.rb, spec/parallel_tests/test/runner_spec.rb
Discovered using codespell:
https://github.com/codespell-project/codespell
=> Fix several typos and spelling errors

lib/parallel_tests/test/runner.rb
To address issue https://github.com/grosser/parallel_tests/issues/879
=> Silence undesirable output when --quiet option is used

.github/workflows/test.yml, .rubocop.yml, lib/parallel_tests/cli.rb, lib/parallel_tests/cucumber/scenario_line_logger.rb, lib/parallel_tests/gherkin/runner.rb, lib/parallel_tests/grouper.rb, parallel_tests.gemspec, spec/parallel_tests/rspec/runner_spec.rb, spec/parallel_tests/test/runner_spec.rb, spec/spec_helper.rb
already reverted once because of https://github.com/grosser/parallel_tests/issues/846 but hopefully things got updated and we have less drama now ...
bumping because fixing CI for 2.5 was a pain and I'd like to not repeat that or make contributors suffer though that
=> drop ruby 2.5

Readme.md
PR [#884](https://github.com/grosser/parallel_tests/pull/884) combined both `verbose-process-command` and `verbose-rerun-command` into `verbose-command`  This PR updates the Readme to reflect that change
=> update Readme for PR 884

lib/parallel_tests/spinach/runner.rb
fixes https://github.com/grosser/parallel_tests/issues/936
=> fix gherkin vs runtime logging

lib/parallel_tests/tasks.rb
fixes https://github.com/grosser/parallel_tests/issues/935
=> rails 5.2 compat

Readme.md
ppl running into bugs and then needing to find some obscure readme part is not fun ...
https://github.com/grosser/parallel_tests/issues/941
=> make examples work on zsh and bash

spec/parallel_tests/grouper_spec.rb
=> cleanup specify groups spec
