grosser/parallel_tests

lib/parallel_tests/test/runner.rb, spec/integration_spec.rb, spec/spec_helper.rb
This is the pull request that grosser requested in #204. :) This fixes the `UndefinedConversionError` seen in some Ruby environments (where `Encoding.default_internal` is set and non-ASCII characters are output by tests). Commit message follows.
IO#readpartial assumes it is dealing with binary data and always returns
ASCII-8BIT. However, Ruby environments that have Encoding.default_internal set
will attempt to encode() strings to that encoding when performing the
operations listed here:
http://ruby-doc.org/core-1.9.3/Encoding.html#method-c-default_internal
=> Respect default encoding if present.

lib/parallel_tests/cli.rb
Each process needs its own handle, the lock wasn't actually locking the
way it was.
Proper fix for #386
Repro:
test.rb:
```ruby
require 'tempfile'
def bad(lock, i)
str = "#{i.to_s} #{("a" * 99)}\n" * 1000
lock.flock(File::LOCK_EX)
$stdout.puts str
ensure
lock.flock(File::LOCK_UN)
end
def good(lock, i)
File.open(lock.path, "w+") do |lock|
str = "#{i.to_s} #{("a" * 99)}\n" * 1000
lock.flock(File::LOCK_EX)
$stdout.puts str
end
end
Tempfile.open('test.lock') do |lock|
pids = 100.times.map { |i|
fork {
send ARGV[0], lock, i
}
}.compact
pids.each do |pid|
Process.wait pid
end
end
```
```bash
$ ruby test.rb bad | uniq | wc -l
1014
$ ruby test.rb good | uniq | wc -l
100
```
100 is the right answer.
=> Fix file lock

lib/parallel_tests/cli.rb
An unlock shouldn't be necessary, but I hit a deadlock in our test suite
the second time I built w/ the new locking mechanics.
=> Ensure an unlock

Readme.md, lib/parallel_tests/cli.rb, spec/integration_spec.rb
Fixed a couple of typos in the README (see commits for details).
Additionally documented a section on PARALLEL_TEST_GROUPS and how to use that to load balance.
=> Fix typos in readme and help output

spec/parallel_tests/test/runner_spec.rb
Fixes Runner spec where group items to expected to match order,
even though order is irrelevant - this test fails every I try.
The solution is to use sets of sets. Other tests may be affected but they'd
have to be made to fail first.
=> fix broken spec

.travis.yml, Gemfile.lock, lib/parallel_tests/cli.rb, spec/fixtures/rails32/Gemfile.lock, spec/fixtures/rails42/Gemfile.lock, spec/integration_spec.rb, spec/parallel_tests/cli_spec.rb, spec/rails_spec.rb
This seems like a simple bug. If I have two files (one spec in each file) then I expect 1 spec per process (2 processes for 2 specs). The current behavior is 4 processes which doesn't make sense.
Before:
```
$ parallel_rspec spec/
4 processes for 2 specs, ~ 0 specs per process
```
After:
```
$ parallel_rspec spec/
2 processes for 2 specs, ~ 1 specs per process
```
=> Reject empty groups

.rspec
When I run the tests locally, I get the following error (not sure why this doesn't happen on travis).
```
$ bundle exec rake
rspec spec/
./parallel_tests/spec/fixtures/rails32/vendor/bundle/ruby/2.0.0/gems/rack-test-0.6.3/spec/rack/test/cookie_spec.rb:3:in `<top (required)>': uninitialized constant Rack (NameError)
from ~/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1327:in `load'
from ~/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1327:in `block in load_spec_files'
from ~/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1325:in `each'
from ~/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/con …
```
=> Makes sure tests in fixtures aren't run accidentally

Readme.md, lib/parallel_tests/cli.rb, lib/parallel_tests/test/runner.rb, spec/parallel_tests/cli_spec.rb, spec/parallel_tests/test/runner_spec.rb
This pull request adds the ability to modify the suffix regexp based on a command line option `--suffix [PATTERN]`. This then modifies the search function to replace `test_suffix`.
This was recommended as the non-invasive version of #436 which allows me to create a gem to use that suffix, or use it directly.
Many thanks for considering this so that we don't have to fork!
=> Ability to modify suffix for tests via a cli option

lib/parallel_tests/cli.rb, spec/integration_spec.rb
The --only-group option is very handy for splitting a task across machines.
If Machine A has 4 cores and Machine B has 2 cores, you could run
on Machine A: -n 6 --only-group 1,2,3,4
on Machine B: -n 6 --only-group 5,6
and have the entire task run. Currently the --only-group option is only respected when running tests. This commit would allow it to be used for any arbitrary command (with the -e flag).
Just don't forget to aggregate your results at the end!
=> Allow use of the 'only-group' option when executing commands in parallel

lib/parallel_tests/cli.rb, lib/parallel_tests/cucumber/runner.rb, lib/parallel_tests/test/runner.rb, spec/integration_spec.rb, spec/parallel_tests/cli_spec.rb, spec/parallel_tests/cucumber/runner_spec.rb, spec/parallel_tests/test/runner_spec.rb
This adds additional reporting on the commands that caused a failing test. This helps massively in finding tests that depend on the order they were run in or the group that they were run in.
This pull request always prints the report, however this could be made optional. However, I feel it's in keeping with the generalized reporting approach taken by tools such as `rspec`.
=> Print out commands that led to failing tests

lib/parallel_tests/cli.rb, spec/parallel_tests/rspec/runner_spec.rb
I don't know very much about rake tasks, so I don't know how to fix if it is running with rake, but this fixes bundle exec parallel_rspec.
=> Disable Spring by default when running executable - #301

lib/parallel_tests/tasks.rb
Our Jenkins jobs have names with spaces and this change makes parallel_tests run with no problems.
=> Fix system calls from a directory names that includes spaces

Readme.md
http://pivotallabs.com/users/miked/blog/articles/849-parallelize-your-rspec-suite is no longer available.
=> Update inspiration link on readme

Readme.md, lib/parallel_tests.rb, lib/parallel_tests/cli.rb, lib/parallel_tests/test/runner.rb, spec/parallel_tests/cli_spec.rb, spec/parallel_tests/test/runner_spec.rb, spec/parallel_tests_spec.rb
See README changes and discussion on grosser/parallel_tests#297 for motivation.
The implementation allows for switching via either an environment variable or a command-line switch for the `parallel_test` executable, similar to `PARALLEL_TEST_PROCESSORS` and `-n`.
The env var is `PARALLEL_TEST_USE_TEST_ENV_NUMBER_FOR_FIRST_PROCESS` and the command line option is `--use-test-env-number-for-first-process`. I'm happy to change these to something less verbose.
=> Add option to use TEST_ENV_NUMBER="1" for first process

Readme.md, lib/parallel_tests/tasks.rb
Just a small sync of both interfaces.
=> Allow limiting parallel:rake to X parallel runs

Readme.md, lib/parallel_tests/tasks.rb, spec/parallel_tests/tasks_spec.rb
**Context**: While using parallel tests on CI we need to recreate and load schema for every build
**Problem**: Running parallel:create parallel:load_schema - load environment twice for each process.
**Solution**: Single Rails rake task to create and load schema with single command without reloading environment.
=> Rake Db Setup Task

lib/parallel_tests/rspec/runner.rb, spec/parallel_tests/rspec/runner_spec.rb
Hey,
This patch fixes the result line matching to ignore rspec's
"pending" failures which rspec claims to not hurt the test suite's
overall status.
=> Ignore rspec "pending failures".

lib/parallel_tests/cli.rb, spec/integration_spec.rb
This adds a `--progress` option that will simply print out a `.` every 60 seconds until the first parallel thread finishes.
The main reason for this change is for CI environments that treat no output as something going wrong. So, when using `--serialize-output`, nothing could be output for a while, so CI thinks the process failed. This prevents this by essentially providing a "heartbeat", until the first parallel task completes and displays its output.
=> Progress indicator option

lib/parallel_tests/tasks.rb, spec/rails_spec.rb
In Rails 5 this can fail due to the new security setup surrounding the migrations. See #520 
Similar to #519 I added the environment variable to turn off this behaviour. I also added a test for this, but I'm not sure if it's at the right place and if it should be executed for all version of Rails or not.
=> Support dropping and afterwards creating the DBs with Rails 5

lib/parallel_tests/rspec/runner.rb, spec/parallel_tests/rspec/runner_spec.rb
Hi
Current ignore rspec pending failures is tested as ```Got 1 failure:```.
But sometimes rspec print as ```Got x failure and x other error:``` . (https://github.com/rspec/rspec-core/blob/fc767bef47807008899c24a8fd919236567c9023/lib/rspec/core/formatters/exception_presenter.rb#L484-L489) So, if it is printed, failed to detect result line.
I know [this  commit]( https://github.com/grosser/parallel_tests/commit/f16ffc9fd0d4cbd061d500da3070ece729f59edd) refactor ```line_is_result?```. But,  I think ```line =~ /\d+ examples?, \d+ failures?/``` seems to be simply and easy to understand for rspec.
thanks.
=> Fix ignore rspec pending failures.

.travis.yml, lib/parallel_tests/rspec/runner.rb, spec/parallel_tests/rspec/runner_spec.rb
`rspec --order random` would have ` --order rand` removed and output `rspecom`.
=> Fix RSpec::Runner.command_with_seed

lib/parallel_tests/cucumber/runner.rb, lib/parallel_tests/rspec/runner.rb, lib/parallel_tests/test/runner.rb, spec/parallel_tests/cucumber/runner_spec.rb, spec/parallel_tests/rspec/runner_spec.rb, spec/parallel_tests/test/runner_spec.rb
@bquorning 
fixing the weird old regex and making the rspec regexp also have boundaries and do everything in a single match
hope that will be less bugs and nobody needs to add new logic since that covers all frameworks ...
the other thing I did not really think about was why the color/tty option needed to be removed ... 
that is to make the result matching work ?
I'd rather have a `remove_color_flags` or so method for that ... and cleanly remove `\s--color\b` and tty ...
rework for https://github.com/grosser/parallel_tests/pull/536
=> moving seeding logic into 1 place

Readme.md, lib/parallel_tests/cucumber/scenario_line_logger.rb, lib/parallel_tests/cucumber/scenarios.rb, spec/integration_spec.rb, spec/parallel_tests/cucumber/scenarios_spec.rb
This PR fixes the --group-by scenarios option for Cucumber.
Previously parallel_tests was using the previous API of Gherkin to use this feature. Unfortunately, different API has changed since the version 2.0 of cucumber.
Previously we use the class `::Cucumber::Runtime::FeaturesLoader` to load a feature, we now use the class `::Cucumber::Core::Gherkin::Document` which gives us way more details about a scenario.
This PR does not support scenario outline however, more works needs to do for this part.
=> Fixed: --group-by scenatios did not work anymore with the new version of Cucumber and Gherkin

lib/parallel_tests/cucumber/scenario_line_logger.rb, lib/parallel_tests/cucumber/scenarios.rb, spec/integration_spec.rb, spec/parallel_tests/cucumber/scenarios_spec.rb
Fixed --group-by scenario for latest cucumber
- Scenario Outline tagging and example table tagging is accounted for
- Feature tagging is accounted for
Cucumber dry run number of scenarios matches parallel test output now.
=> Fix group by scenarios

lib/parallel_tests/rspec/failures_logger.rb, lib/parallel_tests/rspec/logger_base.rb, lib/parallel_tests/rspec/runner.rb, lib/parallel_tests/rspec/runtime_logger.rb, lib/parallel_tests/rspec/summary_logger.rb, spec/parallel_tests/rspec/runner_spec.rb, spec/parallel_tests/rspec/runtime_logger_spec.rb
I’m not sure how many people still use RSpec 1, but I’m pretty sure the number is low enough to warrant this code cleanup. The idea was discussed already 5 years ago, in #98.
@grosser, I’m running into an issue with the runner that used to check the `version` based on the name of the executable; if the executable doesn’t contain the word `rspec`, we think (thought) it was RSpec v1. When running the runner_spec.rb there are some tests that set
```
allow(File).to receive(:file?).with('script/spec').and_return true
```
even one that claims to test RSpec 2 behavior: https://github.com/grosser/parallel_tests/blob/b6a2ecec90a7c370d49ee6a10f3b3d747604d61d/spec/parallel_tests/rspec/runner_spec.rb#L68-L69
=> Remove RSpec 1 compatibility

lib/parallel_tests/tasks.rb, spec/parallel_tests/tasks_spec.rb
Similar to the other `db` tasks, we need to account for the task existing under the `app` namespace (for engines).  This first checks if `db:test:purge` exists, and if it doesn't, falls back to `app:db:test:purge`.  Also added test coverage for `purge_before_load`.
=> Support app namespace when running db:test:purge task

Readme.md
It took me quite a while to figure out how to setup custom runtime log correctly.
This PR adds a section in readme with the setup instructions.
=> Provide custom runtime log file instructions

lib/parallel_tests/test/runner.rb, spec/parallel_tests/test/runner_spec.rb, spec/spec_helper.rb
In case of example containing `:` like `some_spec.rb[1:2:3]` or 'some:spec.rb' runtimes file will contain records like
```
some_spec.rb[1:2:3]:123
some:spec.rb:321
```
and parsed file will have wrong name/runtime statistic.
=> Runtime stat with test names containing colons symbol

lib/parallel_tests/tasks.rb
Here is the result of running the `rake -T` command in Rails application.
```console
% bin/rake -T
(snip)
rake initializers                                      # Print out all defined initializers in the order they are invoked by Rails
rake log:clear                                         # Truncates all/specified *.log files in log/ to zero bytes (specify which logs wit...
rake middleware                                        # Prints out your Rack middleware stack
rake notes                                             # Enumerate all annotations (use notes:optimize, :fixme, :todo for focus)
rake notes:custom                                      # Enumerate a custom annotation, specify with ANNOTATION=CUSTOM
rake parallel:create[count]                            # create test …
```
=> Capitalize the description lines of rake tasks

lib/parallel_tests/cucumber/scenario_line_logger.rb, lib/parallel_tests/cucumber/scenarios.rb, spec/parallel_tests/cucumber/scenarios_spec.rb
File paths can now be used to specify individual tests via line numbers when grouping by scenarios.
- I did not add the functionality to feature grouping because I'm not sure if it even makes sense to specify individual tests but still organize by feature
=> Handle line number in file paths

lib/parallel_tests/gherkin/runner.rb, lib/parallel_tests/rspec/runner.rb, lib/parallel_tests/tasks.rb, lib/parallel_tests/test/runner.rb, spec/parallel_tests/tasks_spec.rb
This change fixes rake tasks on Windows. The only place where adding
ruby binary is necessary for bin/parallel_* binaries. For all other
cases it may leads to some ambiguous command lines like
`ruby.exe ruby rake` which don't work.
=> Use ParallelTests.with_ruby_binary only for bin/parallel_* binaries

lib/parallel_tests.rb, lib/parallel_tests/cli.rb, lib/parallel_tests/pids.rb, spec/integration_spec.rb, spec/parallel_tests/pids_spec.rb, spec/parallel_tests_spec.rb
Now that we're keeping track of pids, how about a graceful shutdown approach that sends the kill signal to the children. Let me know what you think.
=> Allow for graceful shutdown of child processes

Readme.md
This PR clarifies the Test by Pattern section in Readme by indicating that it is to be used with Regex. It also adds an example for excluding a directory.
=> Updating Readme to clarify pattern matching section

lib/parallel_tests/tasks.rb
Heya heya. I use `parallel_tests` heavily during development, because we have some large test suites, and I like to continuously verify that I didn't break anything as I go. This means I use `rake parallel:migrate` during feature development, which means I inevitably will need `rake parallel:rollback` when I screw things up. :)
This happened today, thus this PR.
=> Add parallel:rollback rake task

Readme.md, lib/parallel_tests/cli.rb, lib/parallel_tests/test/runner.rb, spec/parallel_tests/test/runner_spec.rb
This makes it possible to match up output lines when running without --serialize-stdout. This is useful to debug tests that hang when running in parallel by giving real-time feedback and being able to link that feedback to certain potentially problematic tests.
=> Option to prefix the test env number to the output

lib/parallel_tests/cucumber/runner.rb, lib/parallel_tests/gherkin/runner.rb, spec/parallel_tests/cucumber/runner_spec.rb, spec/parallel_tests/gherkin/runner_behaviour.rb
Cucumber has added flaky test support via the `--retry n` command line option, so let's teach parallel_tests about it, too.
=> Cucumber flaky test support

lib/parallel_tests/test/runner.rb
Using [forking_test_runner](https://github.com/grosser/forking_test_runner), took me a while to understand what `Too little runtime info` meant, so trying to make it more explicit.
/cc @grosser 
Low. Just updating error message.
=> Parallel::Test::Runner.sort_by_runtime: improved error message

Readme.md
Just noticed this typo and [checked the code](https://github.com/grosser/parallel_tests/blob/master/lib/parallel_tests/rspec/runner.rb#L30) to confirm that `tmp/parallel_runtime_rspec.log` is correct.
=> Fix typo in README documentation

lib/parallel_tests/tasks.rb, spec/parallel_tests/tasks_spec.rb
We needed our rake task to use the alternate runtime log option which the CLI provides, but we did not want to plumb through one specific option. Instead we surfaced a pass-through field which allows the rake user to specify any number of arbitrary options to pass along to the CLI.
This allows us to have our rake task specify a different runtime-log.
=> Rake task passes through additional arguments

Readme.md, lib/parallel_tests/test/runner.rb, spec/integration_spec.rb, spec/parallel_tests/test/runner_spec.rb
With this combination of flags, all commands will be printed first, and then all outputs. I think it's more useful to print each command followed by its output in sequence.
```
Using recorded test runtime
4 processes for 98 specs, ~ 24 specs per process
bundle exec rspec --color --tty -O .rspec_parallel spec/bug_report_templates_spec.rb spec/requests/memory_spec.rb spec/requests/stylesheets_spec.rb spec/unit/active_admin_spec.rb spec/unit/authorization/index_overriding_spec.rb spec/unit/auto_link_spec.rb spec/unit/batch_actions/resource_spec.rb spec/unit/csv_builder_spec.rb spec/unit/dependency_spec.rb spec/unit/localizers/resource_localizer_spec.rb spec/unit/menu_collection_spec.rb spec/unit/menu_item_spec.rb spec/unit/namespace/register_page_spec.rb …
```
=> Improve verbose + serialize-output usage

lib/parallel_tests/gherkin/runtime_logger.rb
This PR updates the Gherkin runtime_logger formatter to use the new Cucumber events API. This shouldn't affect application behaviour but will fix the deprecation warnings brought up in [this issue against Cucumber](https://github.com/cucumber/cucumber-ruby/issues/1294).
=> Update formatter to use Cucumber events API instead of deprecated API

Gemfile.lock, lib/parallel_tests/tasks.rb, lib/parallel_tests/version.rb, spec/fixtures/rails51/Gemfile.lock, spec/fixtures/rails52/Gemfile.lock, spec/parallel_tests/tasks_spec.rb
Switches to using [`db:purge`](https://github.com/rails/rails/blob/58999af99fa485f748ab33d4aa4254a4b4a50991/activerecord/lib/active_record/railties/databases.rake#L69) over [`db:test:purge`](https://github.com/rails/rails/blob/58999af99fa485f748ab33d4aa4254a4b4a50991/activerecord/lib/active_record/railties/databases.rake#L380).
`db:purge`:
> desc "Empty the database from DATABASE_URL or config/database.yml for the current RAILS_ENV (use db:purge:all to purge all databases in the config). Without RAILS_ENV it defaults to purging the development and test databases."
`db:test:purge` hardcodes loading configuration for an environment named test. `db:purge` will load the environment for whatever `RAILS_ENV` is set to (or fallback).
Here within parallel_tests `purge_before_load` is used on …
=> Support alternate rails environment names for tests

lib/parallel_tests/cli.rb, spec/integration_spec.rb
I'm having a problem when running parallel tests with the `--serialize-stdout` flag, where our CI times out due to receiving no stdout _after_ the first parallel thread finishes, but before other threads are finished. 
The [simulate_output_for_ci](https://github.com/grosser/parallel_tests/blob/06656a00f5a18a5703e7728ed8614827d3ec0409/lib/parallel_tests/cli.rb#L334-L342) method (from issue #512) fixes this issue up to the point when the first parallel thread finishes by printing a dot (`.`) to stdout every 60 seconds, but does not continue printing output after the first parallel thread finishes. I am proposing the dots should continue being printed to stdout until all parallel threads are finished.
An example of when this problem might occur. My CI times out after 5 minutes without …
=> Simulate output for CI after the first parallel thread finishes

Readme.md, lib/parallel_tests/cli.rb, lib/parallel_tests/test/runner.rb, spec/fixtures/rails51/Gemfile.lock, spec/fixtures/rails52/Gemfile.lock, spec/integration_spec.rb, spec/parallel_tests/cli_spec.rb
Add the ability to pass `--exclude-pattern`
fixes #647 
fixes #573
=> add exclude pattern option

lib/parallel_tests/test/runner.rb
cleanup for https://github.com/grosser/parallel_tests/pull/682
fyi @nc-annenk
=> cleanup pattern matching

Readme.md, lib/parallel_tests/cli.rb, lib/parallel_tests/test/runner.rb, spec/integration_spec.rb, spec/parallel_tests/cli_spec.rb
replaces https://github.com/grosser/parallel_tests/pull/694 
--verbose currently displays both the command to be executed by each parallel
process before the tests run, and, on failure of a process, the command
needed to rerun the failing process.
We prefer to display only the latter.
This patch adds flags that can be used instead of --verbose to enable
either the per-process command, or the rerun command, or both.
--verbose-process-command will show the per-process commands, even if
--verbose is not set, or --quiet is set.
--verbose-rerun-command will show the rerun command, even if --verbose
is not set, or --quiet is set.
If --verbose is set, both types of command will be displayed, regardless
of whether the flags for those commands are set or not.
@alboyadjian
=> add additional verbosity options

parallel_tests.gemspec
Hello!
I've forked `parallel_tests` and like to use a [local git repo with Bundler](https://bundler.io/v1.16/bundle_config.html#LOCAL-GIT-REPOS) to test some changes. Unfortunately Bundler is crashing with this error:
```
Invalid gemspec in [/Users/ndbroadbent/code/parallel_tests/parallel_tests.gemspec]: cannot load such file -- ./lib/parallel_tests/version
```
I was able to fix the issue by changing this require call to use `require_relative`.
=> Fix Invalid gemspec in parallel_tests.gemspec: cannot load such file -- ./lib/parallel_tests/version

Readme.md
It took me a while to figure out why I couldn't get Spring to work, so I wanted to add this to the Readme and make it a bit clearer.
See https://github.com/grosser/parallel_tests/issues/729#issuecomment-562836419
EDIT: Actually I've realized that I am able to patch Spring to fix the database issue, and also set the default value of `DISABLE_SPRING` to `"0"` in my [`spring-commands-parallel-tests` gem](https://github.com/DocSpring/spring-commands-parallel-tests) (since this code runs before parallel_tests.) So I might just update the README with instructions to use this gem, if that's ok!
=> Add note about using the spring-commands-parallel-tests gem to automatically patch and enable Spring

Readme.md, lib/parallel_tests/tasks.rb
Also added a link to the docs.
UPDATE: It looks these builds are failing because of a flaky spec:
* https://travis-ci.org/grosser/parallel_tests/jobs/621973707?utm_medium=notification&utm_source=github_status
* https://travis-ci.org/grosser/parallel_tests/jobs/621973710?utm_medium=notification&utm_source=github_status
=> Update suggestion in readme to use the :sql schema format. Support db:structure:dump and load structure in parallel

Readme.md, lib/parallel_tests/tasks.rb
=> cleanup task logic more

parallel_tests.gemspec
Add `bug_tracker_uri`, `wiki_uri`, `documentation_uri`, and `source_code_uri` to the gemspec metadata.
These [project metadata](https://guides.rubygems.org/specification-reference/#metadata) will facilitate easy access to project information. The URI will be available on the [Rubygems project page](https://rubygems.org/gems/parallel_tests), via the rubygems API, and the `gem` and `bundle` command-line tools with the next release.
=> Add project metadata to the gemspec

.travis.yml, spec/integration_spec.rb, spec/parallel_tests/cli_spec.rb, spec/rails_spec.rb, spec/spec_helper.rb
See the description and comments in #735
These tests are run in parallel threads, so there are no guarantees about the execution order.
I've also removed the `Timeout.timeout` block around each example, because that seemed to swallow the actual error and make it much harder to figure out why random tests were crashing. (And nothing seems to be hanging anymore.)
EDIT: I'll also throw in the commit to cache the gems in `spec/fixtures/rails51/vendor/bundle` and `spec/fixtures/rails52/vendor/bundle`, because that speeds up the CI builds.
=> Fix a number of flaky tests (.ordered expectation in multiple threads, and unstable output expectations)

spec/rails_spec.rb, spec/spec_helper.rb
followup to https://github.com/rails/rails/pull/34027
=> bring back test timeouts

lib/parallel_tests/cli.rb, spec/parallel_tests/cli_spec.rb
When starts with relative paths, an example:
`bundle exec parallel_rspec ./spec` 
relative paths are passed to the test runner and they do not match the paths in the runtime log.
=> Clean file path from cli

Readme.md
Adds reference to `parallel_split_test` in the Tips section of the Readme.
As per: https://github.com/grosser/parallel_tests/issues/747#issuecomment-581176002
=> Add 'parallel_split_test' to Tips in Readme

lib/parallel_tests/cli.rb, lib/parallel_tests/rspec/runner.rb, lib/parallel_tests/test/runner.rb
https://github.com/grosser/parallel_tests/pull/757
=> remove name override logic that never worked

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
Hi Michael. I just upgraded to 3, and it seems to be working fine. I thought I'd add a changelog to help other people to upgrade.
[Fixes #677]
=> Introduce Changelog and PR template

Readme.md
=> Highlight availability of ParallelTests module

CHANGELOG.md, lib/parallel_tests/tasks.rb, spec/parallel_tests/tasks_spec.rb
After #732, if you're using the SQL schema format, `parallel:prepare` now calls `db:purge db:structure:load` where it used to call `db:test:prepare`. The old task forced using the test environment, however the new tasks make no assumptions about the environment. Therefore, when combined with a Spring-ified rake binstub, where Spring defaults to the development environment, when `parallel:prepare` calls `db:purge db:structure:load`, they're running in the development environment against the development database, instead of in the test environment against the test database.
Now the environment is forced to be "test" in all rake tasks regardless of the RAILS_ENV that might have been set, whether by Spring or the user. This has the side-effect of removing the ability to run the tasks in a …
=> Force RAILS_ENV to be "test" in rake tasks

CHANGELOG.md, lib/parallel_tests/rspec/runner.rb, spec/parallel_tests/rspec/runner_spec.rb
RSpec colorizes its results based on if there are any failures (red), pending (orange) or none of the above (green).
The method used to summarize the results from the various threads, `summarize_results` was not doing this colorization.
This commit applies the same colorization that RSpec does, utilizing RSpec::Core helpers to do so.
=> Colorize summarized RSpec results.

Readme.md, lib/parallel_tests/cli.rb
[optparse documentation](https://ruby-doc.org/stdlib-2.6.6/libdoc/optparse/rdoc/OptionParser.html) says that Array type flags are "Strings separated by ',' (e.g. 1,2,3)". And indeed `--only-group 1, 2, 3` only tests group 1.
- [-] Added tests.
- [-] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new 
=> Remove spaces in --only-group flag documentation

CHANGELOG.md, Readme.md, lib/parallel_tests/cli.rb, lib/parallel_tests/grouper.rb, spec/parallel_tests/cli_spec.rb, spec/parallel_tests/grouper_spec.rb, spec/parallel_tests/test/runner_spec.rb
At my organization, we heavily use this gem.  We sometimes run with 40-50 parallel processes with giant VMs in AWS.  
Our test suite has a lot of data-intensive tests.  We have plans to refactor these at an architecture level, but at the moment, it is a fact of life. 
When using this gem, its possible for these data-intensive tests to be shuffled so they run alongside each other.  This makes them a bit more flaky, but, more importantly, it makes them take much longer when they are competing with each other for data.
I wanted to use `--single` and `--isolate-n` to help with this issue, however, the specs in `--single` are still shuffled into parallel processes by size. There is not full control over them. So it was still possible for these tests to still collide with each other.
Maybe this …
=> Specify groups argument

CHANGELOG.md, lib/parallel_tests/tasks.rb
fix https://github.com/grosser/parallel_tests/issues/801
deprecation explanation in Rails 6.1 (will be removed in Rails 6.2): https://blog.saeloun.com/2020/09/30/rails-deprecates-db-structure-commands.html
=> replace deprecated db:structure by db:schema

lib/parallel_tests/tasks.rb
Fix https://github.com/grosser/parallel_tests/pull/803
Fix for a bug in the code, `type` variable was only defined for rails version `< 6.1`, for 6.1 or above it was failing with this error
=> fix prepare rake task

CHANGELOG.md, lib/parallel_tests/cli.rb, lib/parallel_tests/cucumber/runner.rb, lib/parallel_tests/gherkin/runner.rb, lib/parallel_tests/rspec/runner.rb, lib/parallel_tests/spinach/runner.rb, lib/parallel_tests/test/runner.rb, spec/integration_spec.rb, spec/parallel_tests/cli_spec.rb
Sometimes, since I'm used to how `rspec` works, I run `parallel_rspec` and I expect it to run all specs.
However, it currently gives the error:
> Pass files or folders to run
This PR proposes to make it work like other test runners, and run all tests by default.
=> Run default test folder if no arguments passed

.github/workflows/test.yml, CHANGELOG.md, Readme.md, lib/parallel_tests/cli.rb, spec/integration_spec.rb
This change-sets adds a `--retain-exit-status` which returns the highest exit status from a test run failure rather than always exiting with 1 when running in parallel.
The use-case for this is test suites that use exit statuses to communicate additional information besides failure such as marking a suite as unstable.
This treats an exit status of 1 as a generic failure which is the default for most suites, and treats any error above 1 as being preferred when present.
This change is backwards compatible for existing test suites that use parallel_tests.
=> Adding --highest-exit-status which returns the highest exit status from test runs

CHANGELOG.md, lib/parallel_tests/gherkin/runner.rb, spec/fixtures/rails60/Gemfile.lock, spec/fixtures/rails61/Gemfile.lock, spec/parallel_tests/gherkin/runner_behaviour.rb
Update running command to pass cucumber profile as the last argument (And permit --retry flag to work).
=> Permit parallel_tests/cucumber running to allow --retry flag

CHANGELOG.md
Changelog entry was missing v3.7.1 entry and seems that `Unreleased` section is contained this change
=> Fix missing v3.7.1 changelog entry

lib/parallel_tests/test/runner.rb, spec/integration_spec.rb
replaces https://github.com/grosser/parallel_tests/pull/831
fixes #727
@swiknaba
=> allow running test files with multiple spaces

spec/parallel_tests/test/runner_spec.rb
Fixes the following failure when running the test in isolation:
$ bundle exec rspec spec/parallel_tests/test/runner_spec.rb
1) ParallelTests::Test::Runner.test_in_groups when passed runtime groups by size and uses specified groups of specs in specific order in specific processes
Failure/Error: actual = groups.map(&:to_set).to_set
NoMethodError:
undefined method `to_set' for ["ddd", "eee"]:Array
actual = groups.map(&:to_set).to_set
^^^^
=> Require "set" module in spec/parallel_tests/test/runner_spec.rb

lib/parallel_tests/cli.rb
Obsolete since e36fa9f8235844afabba624eb58549ad58ddc9ef.
The subprocesses were switched to using IO.popen which passes
environment variables. The subprocess command no longer includes export.
=> Remove obsolete export statement filter in lib/parallel_tests/cli.rb

spec/integration_spec.rb, spec/spec_helper.rb
FileUtils.mkpath already checks if a directory exists before creating
it, so there is no need to do so again. Avoid the extra system call when
it is unnecessary.
=> Remove redundant File.exists? checks in specs

spec/rails_spec.rb
Avoid a subprocess and shell to the rm program. Slightly more
effiencient to delete directly.!
=> Use FileUtils.rm_f to delete files in specs

lib/parallel_tests/tasks.rb, spec/integration_spec.rb, spec/parallel_tests/rspec/runtime_logger_spec.rb, spec/parallel_tests/tasks_spec.rb, spec/parallel_tests/test/runner_spec.rb, spec/parallel_tests/test/runtime_logger_spec.rb, spec/rails_spec.rb
Treat subprocesses commands as an array of strings. This avoid the need
to include a shell in the subprocess. Instead, the commands execute
directly. As well, there is no need to parse or format shell
syntax (such as string quoting).
=> Avoid using a shell for subprocesses during tests

CHANGELOG.md, lib/parallel_tests.rb, lib/parallel_tests/cli.rb, lib/parallel_tests/cucumber/runner.rb, lib/parallel_tests/cucumber/scenarios.rb, lib/parallel_tests/gherkin/runner.rb, lib/parallel_tests/rspec/runner.rb, lib/parallel_tests/tasks.rb, lib/parallel_tests/test/runner.rb, spec/integration_spec.rb, spec/parallel_tests/cli_spec.rb, spec/parallel_tests/cucumber/runner_spec.rb, spec/parallel_tests/cucumber/scenarios_spec.rb, spec/parallel_tests/gherkin/runner_behaviour.rb, spec/parallel_tests/rspec/runner_spec.rb, spec/parallel_tests/tasks_spec.rb, spec/parallel_tests/test/runner_spec.rb, spec/parallel_tests_spec.rb, spec/spec_helper.rb
Treat subprocess commands as an array of strings. This avoid the need to
include a shell in the subprocess. Instead, the commands execute
directly. As well, there is less need to parse or format shell
syntax (such as string quoting).
Continue to handle IO redirection through IO.popen.
As a caution, this may be considered a backward incompatible change if
users are relying on injecting shell features through the CLI. I don't
expect this to be an issue in practice, but am raising it just in case.
It would be best to apply a major version bump before release to
maintain semantic versioning.
=> Changed subprocesses to execute without a shell.

lib/parallel_tests/tasks.rb, spec/integration_spec.rb
In the event of a error or spec failure, it is often easier to debug a
problem when the path is expanded to its canonical form rather than
being many dots. These paths can sometimes appear in an error.
=> Alwasy use expanded canonical paths

.github/PULL_REQUEST_TEMPLATE.md, Readme.md
Many editors clean up trailing white space on save. By removing it all
in one go, it helps keep future diffs cleaner by avoiding spurious white
space changes on unrelated lines.
=> Trim trailing white space throughout the project

lib/parallel_tests/tasks.rb, spec/parallel_tests/tasks_spec.rb
`|| test 1` is equivalent to `true` which always returns a exit status
of 0. Using true is more explicit. See: https://linux.die.net/man/1/true
`&& test 1` is equivalent to using the exit status of the preceding
command, so just use it and avoid the extra syntax.
`&& test` is equivalent to `false` which always returns a exit status of
1. Using false is more explicit. See: https://linux.die.net/man/1/false
=> Simplify use of command "test" in subprocesses

lib/parallel_tests/tasks.rb
If /bin/bash does not exist, system will return nil. Avoid checking
twice to reduce the total number of system calls.
https://ruby-doc.org/core-2.5.0/Kernel.html#method-i-system
> system returns true if the command gives zero exit status, false for
> non zero exit status. Returns nil if command execution fails.
=> Remove redundant File.executable?('/bin/bash') check

spec/fixtures/rails60/Gemfile.lock, spec/fixtures/rails61/Gemfile.lock, spec/fixtures/rails70/Gemfile.lock, spec/rails_spec.rb
Through the use of `bundle install` these files change on a test run if
the parallel_tests version changes.
For example, right now parallel_tests is version 3.8.1 but is specified
as 3.8.0 in spec/fixtures/rails70/Gemfile.lock. Running rspec results in
a undesired change to this file. When submitting pull requests, it is
best practice to avoid unrelated changes, so this slightly slows down a
contributor's workflow.
Use the frozen configuration option to ensure that these files are
always up to date. If they are not, CI will fail with a useful message.
See https://bundler.io/man/bundle-config.1.html
> frozen (BUNDLE_FROZEN): Disallow changes to the Gemfile. When the
> Gemfile is changed and the lockfile has not been updated, running
> Bundler commands will be blocked. Defaults to true when …
=> Install spec/fixtures/**/Gemfile in frozen mode

CHANGELOG.md, lib/parallel_tests/test/runner.rb, spec/parallel_tests/test/runner_spec.rb
Currently, we raise a generic `RuntimeError` when the runtime log is too
small. This can make it hard for calling code to handle the situation.
The best that can be done is attempting to match on the string error
message.
This change introduces a custom `RuntimeLogTooSmallError` that calling
code can more easily rescue. This will make it easier for builds to log
when this event occurs or automatically retry with a different grouping
strategy.
This is a breaking change for anyone who was relying on rescuing
`RuntimeError`.
=> Raise custom error when runtime log is too small

lib/parallel_tests/test/runner.rb, spec/parallel_tests/cli_spec.rb, spec/parallel_tests/test/runner_spec.rb
verified with https://github.com/uyuni-project/uyuni
`rake parallel:sanity_check`
=> bring back env replacement behavior

CHANGELOG.md, lib/parallel_tests/cli.rb, lib/parallel_tests/test/runner.rb, spec/integration_spec.rb, spec/parallel_tests/cli_spec.rb
This PR combines `--verbose-process-command` and `--verbose-rerun-command` into singel `--verbose-command`.
Also `TEST_ENV_NUMBER` and `PARALLEL_TEST_GROUPS` environment variables added to command output. Useful for debugging purposes.
**Before:**
```
1 process for 1 spec, ~ 1 spec per process
bundle exec rspec spec/xxx_spec.rb
```
**After:**
```
1 process for 1 spec, ~ 1 spec per process
TEST_ENV_NUMBER= PARALLEL_TEST_GROUPS=2 bundle exec rspec spec/xxx_spec.rb
```
=> Prepend env in command output

Readme.md
PR updates the build status badges in the README by:
* removing the travis one (since a job hasn't run there in 2 years)
* updates the GH badge to point at the `test` workflow over `windows`
My best guess is that the README was never updated to reflect the changes from #763.
=> Update build status badges in README

lib/parallel_tests/test/runner.rb
This addresses an issue when manually interrupting the test suite via Ctrl+C in the shell. In particular we've noticed that this can sometimes leave orphaned web browser processes from our selenium feature specs, which then cause various problems until manually terminated.
Tracing the problem I found that it's caused by subprocesses receiving SIGINT twice thus preventing the graceful shutdown that would normally happen. The fix prevents the shell from sending a SIGINT directly to the subprocesses leaving only one SIGINT from the interrupt handler in the `CLI` class.
=> Avoid double sending of SIGINT to subprocesses

CHANGELOG.md, lib/parallel_tests/cli.rb, lib/parallel_tests/test/runner.rb, spec/integration_spec.rb
reproduction:
```
source "https://rubygems.org"
gem "parallel_tests", path: "~/Code/tools/parallel_tests"
gem "minitest"
gem "rspec"
sleep 5; describe { specify { 'Should not get here' }; specify { p 'Should not get here either'} }
require "minitest/autorun"
describe "foo" do
it "do" do
puts "foo"
sleep 10
end
end
trap("SIGINT")  do
puts "GOT INT A"
$stdout.flush
end
```
- run test and Ctrl+c -> 1 GOT INT
- run test and uncomment `binding.irb` shell works
- run spec and interrupt -> does not run tests
issues:
integration test fails ... I think this is because it's not a cgroup so the signal does not reach all tests
so I expect this to also happen on CI which could mean tests hang forever
also tried with `(parallel_rspec test/a_spec.rb -n 2 &)` and then `kill -int` but also worked
=> fix double int without breaking stdin

.github/workflows/test.yml, Gemfile, Gemfile.lock, spec/fixtures/rails70/Gemfile.lock
Ruby 3.2 has [been released](https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/)! Let's add it to the build matrix.
=> CI: add Ruby 3.2 to the test matrix

lib/parallel_tests/grouper.rb, spec/parallel_tests/grouper_spec.rb
We found the duplicate `raise` codes.
Looking at the git history, the last modification to these codes was this PR https://github.com/grosser/parallel_tests/pull/804 .
Therefore, we decided it would be better to use the second `raise` code and remove the first `raise` code.
=> Fix duplicate raise code

lib/parallel_tests/test/runner.rb, spec/integration_spec.rb
Hi. I was trying to create a small script running some custom tests in parallel where I need the TEST_ENV_NUMBER in an other ENV variable, so I naturally tried to reassing it, something like this:
```bash
parallel_test -n 3 --first-is-1 -e 'bash -c "export CI_NODE_TOTAL=3 && export CI_NODE_INDEX=$TEST_ENV_NUMBER && echo $CI_NODE_INDEX / $CI_NODE_TOTAL"'
```
However, it printed `1 / 3` for all processes instead of `1 / 3`, `2 / 3` and `3 / 3`. Then I found [this line](https://github.com/grosser/parallel_tests/blob/f70f2ee0624a318296732cbe149468174cfdd97e/lib/parallel_tests/test/runner.rb#L98) that replaces `$TEST_ENV_NUMBER` and `${TEST_ENV_NUMBER}` with the current number by modifying the original `cmd` array which affects all the other processes as there won't be `$TEST_ENV_NUMBER` …
=> Fix $TEST_ENV_NUMBER replacing code to not affect all processes

CHANGELOG.md, lib/parallel_tests/rspec/failures_logger.rb, lib/parallel_tests/rspec/logger_base.rb, lib/parallel_tests/rspec/runtime_logger.rb, lib/parallel_tests/rspec/summary_logger.rb, spec/parallel_tests/rspec/runtime_logger_spec.rb
RSpec 3 was released 9 years ago. Most people will have upgraded by now 😅
=> Remove compatibility with RSpec 2

.rubocop.yml, Gemfile, Gemfile.lock, lib/parallel_tests/cli.rb, lib/parallel_tests/rspec/runtime_logger.rb, spec/parallel_tests/test/runner_spec.rb
Ruby 2.5 compatibility is no longer a concern, so we can now upgrade to the very latest version.
=> Upgrade RuboCop and fix some offenses

CHANGELOG.md, Readme.md, lib/parallel_tests/cli.rb
The documentation says that parallel_test will attempt to use a runtime
grouping strategy if a runtime file is present and otherwise fall back
to the filesize strategy. This behavior can be overridden with an
explicit `--group-by` flag.
The `--only-group` flag changes this by always running with the filesize
strategy when no explicit strategy is given, even if a runtime file is
present. This happens in `lib/parallel_tests/cli.rb:312`.
I was attempting to rely on the default behavior and also use the
`--only-group` flag and couldn't figure out why my runtime log wasn't
getting used. Only by reading the source did I figure out this
undocumented edge-case in the `--only-group` flag.
This commit adds explicit documentation about this. If you want to use
the `--only-group` flag and a runtime …
=> Document `--only-group` grouping strategy choice

CHANGELOG.md, lib/parallel_tests/rspec/runner.rb, spec/parallel_tests/rspec/runner_spec.rb
fixes https://github.com/grosser/parallel_tests/issues/271
:information_source: tested in real project as well
**before**
```
bin/parallel_rspec spec/acceptance/              
0 processes for 0 specs, ~ 0 specs per process 
```
**after**
```
bin/parallel_rspec spec/acceptance/                                                                                                             
1 process for 40 specs, ~ 40 specs per process
...
```
=> Support also feature files used by RSpec turnip gem.

Readme.md, lib/parallel_tests/rspec/verbose_logger.rb, spec/parallel_tests/rspec/verbose_logger_spec.rb, spec/spec_helper.rb
for https://github.com/grosser/parallel_tests/pull/926
@jdufresne
=> unify verbose formatter with other loggers

CHANGELOG.md, Readme.md, lib/parallel_tests/tasks.rb
Added support for performing `create`, `migrate`, `drop`, and `load_schema` on individual databases when using multiple databases in Rails >= 6.1
NOTE: Will add integration tests if desired by maintainer
=> Add support for multiple DBs in Rails >= 6.1

lib/parallel_tests.rb, spec/parallel_tests_spec.rb
Hey! Sometime when using `parallel_rspec --fail-fast --test-options '--fail-fast'`, it can happen that the process is already gone before `stop_all_processes` has time to kill it. In this case `Errno::ESRCH` was raised. Rescuing the error ensures that the exits happen as expected for the parent process itself.
Fix errors like that:
```
bundler: failed to load command: parallel_rspec (/Users/louim/.asdf/installs/ruby/3.0.6/bin/parallel_rspec)
/Users/louim/.gem/ruby/3.0.0/gems/parallel_tests-4.2.1/lib/parallel_tests.rb:46:in `kill': No such process (Errno::ESRCH)
from /Users/louim/.gem/ruby/3.0.0/gems/parallel_tests-4.2.1/lib/parallel_tests.rb:46:in `block in stop_all_processes'
from /Users/louim/.gem/ruby/3.0.0/gems/parallel_tests-4.2.1/lib/parallel_tests.rb:46:in `each'
from …
```
=> Make sure no error is raised when a process is already terminated

CHANGELOG.md, Readme.md, lib/parallel_tests/cli.rb, lib/parallel_tests/test/runner.rb, spec/parallel_tests/cli_spec.rb, spec/parallel_tests/test/runner_spec.rb
> tldr; It's useful to run 1 or more tests multiple times when debugging and I'd like to propose an option to do so with parallel_tests
I often find that I'd like to run 1+ files locally, in parallel, to rule out certain flakey test behaviors (order tests are being run). Kind of like a form of "test fuzzing" I guess? The purpose is to generally rule out the test is flakey.
I often find myself doing something like this in zsh:
repeat 10 bin/rspec path/to/my_spec.rb
Sometimes it's more than 10, and sometimes it's more than 1 file I'd like to run at the same time.
I'd like to do this with parallel_tests instead and I'd like to propose this PR as a potential solution (I didn't see this functionality present with the current options)
Example usage:
```
export TEST_FILES="
spec/test_1.rb …
```
=> Allow for duplicate tests with --allow-duplicates

CHANGELOG.md, lib/parallel_tests/cli.rb, spec/parallel_tests/cli_spec.rb
This is a follow up to #940 
After that PR was merged, I was writing a little helper script that basically let me do `<script> <file>` and it would basically duplicate that file name `sysctl -n hw.ncpu`, and then run parallel_rspec w/ the `--allow-duplicates` flag.
What I discovered was that the `TEST_ENV_NUMBER` was set to the same value for each file. I traced the root behavior back to the small change I made in this PR
=> Allow TEST_ENV_NUMBER to support duplicate file groups

CHANGELOG.md, Readme.md, lib/parallel_tests/cli.rb, spec/parallel_tests/cli_spec.rb
Fixes: #948 
Like: rspec --failure-exit-code=0  (https://rspec.info/features/3-13/rspec-core/command-line/exit-status/ )
I want to execute a command like this.
```shell
bundle exec rake "parallel:spec[--failure-exit-code=0]"
```
=> Add --failure-exit-code option

CHANGELOG.md, Readme.md, lib/parallel_tests/cli.rb, lib/parallel_tests/test/runner.rb, spec/integration_spec.rb, spec/parallel_tests/cli_spec.rb
=> Restore back options --verbose-process-command and --verbose-rerun-command

CHANGELOG.md, lib/parallel_tests/test/runner.rb, parallel_tests.gemspec, spec/parallel_tests/test/runner_spec.rb
This used to work until 7fd751839ee588c5fc8382027a842cf49ad0605c. I think it was an oversight so this change adds the proper shellspliting so that it keeps working.
=> Allow passing custom command lines as "PARALLEL_TESTS_EXECUTABLE"

parallel_tests.gemspec
Hello 👋🏼,
we did the same on premailer/premailer#439
---
Make the gem more secure by requiring that all privileged operations by any of the owners require OTP.
Ref: https://guides.rubygems.org/mfa-requirement-opt-in/
=> Opt-in for MFA requirement

CHANGELOG.md, lib/parallel_tests/cucumber/failures_logger.rb, spec/parallel_tests/cucumber/failure_logger_spec.rb
=> Fix output of ParallelTests::Cucumber::FailuresLogger (fixes #979)

CHANGELOG.md, Readme.md, lib/parallel_tests.rb, lib/parallel_tests/cli.rb, spec/parallel_tests_spec.rb
Currently the CLI accepts `-m` or `--multiply-processes` with a `COUNT` value which is a multiple applied to the number of parallel process to be spun up.
This commit adds the aditional abiity to modify `COUNT` by specifing `PARALLEL_TEST_MULTIPLE` which will be parsed into a float.
=> Allow setting process multiplier via ENV variable

CHANGELOG.md, lib/parallel_tests/cucumber/failures_logger.rb, spec/parallel_tests/cucumber/failure_logger_spec.rb
Currently, using the ParallelTests::Cucumber::FailuresLogger throws a LocalJumpError when the run doesn't have any failed examples. 
=> Fix ParallelTests::Cucumber::FailuresLogger

Readme.md, spec/parallel_tests_spec.rb
- Added `after` block to cleanup `ENV` in specs.
=> Remove extra markdown from Readme and specs

CHANGELOG.md, Readme.md, lib/parallel_tests/cli.rb, lib/parallel_tests/grouper.rb, spec/parallel_tests/grouper_spec.rb
This PR expands the `--specify-groups` option so it can also receive its value from standard input. This avoids problems with command line argument limits of the shell in situations with many thousands of specs.
=> Allow the specify-groups option to receive its value from STDIN

CHANGELOG.md, Readme.md, lib/parallel_tests/cli.rb, lib/parallel_tests/gherkin/runner.rb, lib/parallel_tests/rspec/runner.rb, lib/parallel_tests/test/runner.rb, spec/integration_spec.rb, spec/parallel_tests/cli_spec.rb
Addresses #1007
Added `--exec-args` option, allowing users to run shell commands prior to running the tests in each process.
For example, running `bundle exec parallel_rspec ./spec/parallel_tests/ --exec-args "echo 'hello world'" -n 2 --verbose` will result in
> 2 processes for 17 specs, ~ 8 specs per process
> TEST_ENV_NUMBER= PARALLEL_TEST_GROUPS=2 echo hello\ world \&\& bundle exec rspec --color --tty spec/parallel_tests/gherkin/listener_spec.rb spec/parallel_tests/grouper_spec.rb spec/parallel_tests/rspec/failures_logger_spec.rb spec/parallel_tests/rspec/logger_base_spec.rb spec/parallel_tests/rspec/verbose_logger_spec.rb spec/parallel_tests/tasks_spec.rb spec/parallel_tests/test/runner_spec.rb …
=> enhancement: added exec-args option

CHANGELOG.md, Readme.md, lib/parallel_tests/tasks.rb, spec/parallel_tests/tasks_spec.rb
Based on the debate on https://github.com/grosser/parallel_tests/issues/970, makes `ParallelTests::Tasks.rails_env` be more dynamic being able to run on different Rails environments. 
The change prioritizes the `PARALLEL_RAILS_ENV` value, if it isn't set, it defaults to `test`.
=> Prioritize PARALLEL_RAILS_ENV over the standard
